#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MathCompletionCategory {
    GreekLower,
    GreekUpper,
    Function,
    Operator,
    Relation,
    Arrow,
    Symbol,
    Delimiter,
    Dots,
    Construct,
    Accent,
    Misc,
}

#[derive(Debug, Clone)]
pub struct MathCompletionItem {
    pub command: &'static str,
    pub snippet: &'static str,
    pub description: &'static str,
    pub category: MathCompletionCategory,
}

impl MathCompletionItem {
    pub fn label(&self) -> &str {
        self.command
    }
}

use MathCompletionCategory::*;

const MATH_COMPLETIONS: &[MathCompletionItem] = &[
    // ── Constructs ──
    MathCompletionItem {
        command: "frac",
        snippet: "\\frac{}{}",
        description: "Fraction",
        category: Construct,
    },
    MathCompletionItem {
        command: "sqrt",
        snippet: "\\sqrt{}",
        description: "Square root",
        category: Construct,
    },
    MathCompletionItem {
        command: "overline",
        snippet: "\\overline{}",
        description: "Overline",
        category: Construct,
    },
    MathCompletionItem {
        command: "underline",
        snippet: "\\underline{}",
        description: "Underline",
        category: Construct,
    },
    MathCompletionItem {
        command: "text",
        snippet: "\\text{}",
        description: "Text in math",
        category: Construct,
    },
    MathCompletionItem {
        command: "mathrm",
        snippet: "\\mathrm{}",
        description: "Roman text",
        category: Construct,
    },
    MathCompletionItem {
        command: "left",
        snippet: "\\left(  \\right)",
        description: "Scalable left delimiter",
        category: Delimiter,
    },
    MathCompletionItem {
        command: "right",
        snippet: "\\right)",
        description: "Scalable right delimiter",
        category: Delimiter,
    },
    MathCompletionItem {
        command: "begin",
        snippet: "\\begin{}\n\n\\end{}",
        description: "Begin environment",
        category: Construct,
    },
    MathCompletionItem {
        command: "displaystyle",
        snippet: "\\displaystyle",
        description: "Display style",
        category: Construct,
    },
    MathCompletionItem {
        command: "textstyle",
        snippet: "\\textstyle",
        description: "Text style",
        category: Construct,
    },
    MathCompletionItem {
        command: "limits",
        snippet: "\\limits",
        description: "Force limits above/below",
        category: Construct,
    },
    MathCompletionItem {
        command: "nolimits",
        snippet: "\\nolimits",
        description: "Force limits inline",
        category: Construct,
    },
    // ── Accents ──
    MathCompletionItem {
        command: "hat",
        snippet: "\\hat{}",
        description: "Hat accent",
        category: Accent,
    },
    MathCompletionItem {
        command: "tilde",
        snippet: "\\tilde{}",
        description: "Tilde accent",
        category: Accent,
    },
    MathCompletionItem {
        command: "vec",
        snippet: "\\vec{}",
        description: "Vector arrow",
        category: Accent,
    },
    MathCompletionItem {
        command: "dot",
        snippet: "\\dot{}",
        description: "Dot accent",
        category: Accent,
    },
    MathCompletionItem {
        command: "ddot",
        snippet: "\\ddot{}",
        description: "Double dot accent",
        category: Accent,
    },
    MathCompletionItem {
        command: "bar",
        snippet: "\\bar{}",
        description: "Bar accent / overline",
        category: Accent,
    },
    MathCompletionItem {
        command: "widehat",
        snippet: "\\widehat{}",
        description: "Wide hat",
        category: Accent,
    },
    MathCompletionItem {
        command: "widetilde",
        snippet: "\\widetilde{}",
        description: "Wide tilde",
        category: Accent,
    },
    MathCompletionItem {
        command: "overrightarrow",
        snippet: "\\overrightarrow{}",
        description: "Right arrow above",
        category: Accent,
    },
    MathCompletionItem {
        command: "overleftarrow",
        snippet: "\\overleftarrow{}",
        description: "Left arrow above",
        category: Accent,
    },
    MathCompletionItem {
        command: "overbrace",
        snippet: "\\overbrace{}",
        description: "Overbrace",
        category: Accent,
    },
    MathCompletionItem {
        command: "underbrace",
        snippet: "\\underbrace{}",
        description: "Underbrace",
        category: Accent,
    },
    // ── Greek lowercase ──
    MathCompletionItem { command: "alpha", snippet: "\\alpha", description: "α alpha", category: GreekLower },
    MathCompletionItem { command: "beta", snippet: "\\beta", description: "β beta", category: GreekLower },
    MathCompletionItem { command: "gamma", snippet: "\\gamma", description: "γ gamma", category: GreekLower },
    MathCompletionItem { command: "delta", snippet: "\\delta", description: "δ delta", category: GreekLower },
    MathCompletionItem { command: "epsilon", snippet: "\\epsilon", description: "ε epsilon", category: GreekLower },
    MathCompletionItem { command: "varepsilon", snippet: "\\varepsilon", description: "ε variant epsilon", category: GreekLower },
    MathCompletionItem { command: "zeta", snippet: "\\zeta", description: "ζ zeta", category: GreekLower },
    MathCompletionItem { command: "eta", snippet: "\\eta", description: "η eta", category: GreekLower },
    MathCompletionItem { command: "theta", snippet: "\\theta", description: "θ theta", category: GreekLower },
    MathCompletionItem { command: "vartheta", snippet: "\\vartheta", description: "ϑ variant theta", category: GreekLower },
    MathCompletionItem { command: "iota", snippet: "\\iota", description: "ι iota", category: GreekLower },
    MathCompletionItem { command: "kappa", snippet: "\\kappa", description: "κ kappa", category: GreekLower },
    MathCompletionItem { command: "lambda", snippet: "\\lambda", description: "λ lambda", category: GreekLower },
    MathCompletionItem { command: "mu", snippet: "\\mu", description: "μ mu", category: GreekLower },
    MathCompletionItem { command: "nu", snippet: "\\nu", description: "ν nu", category: GreekLower },
    MathCompletionItem { command: "xi", snippet: "\\xi", description: "ξ xi", category: GreekLower },
    MathCompletionItem { command: "omicron", snippet: "\\omicron", description: "ο omicron", category: GreekLower },
    MathCompletionItem { command: "pi", snippet: "\\pi", description: "π pi", category: GreekLower },
    MathCompletionItem { command: "varpi", snippet: "\\varpi", description: "ϖ variant pi", category: GreekLower },
    MathCompletionItem { command: "rho", snippet: "\\rho", description: "ρ rho", category: GreekLower },
    MathCompletionItem { command: "varrho", snippet: "\\varrho", description: "ϱ variant rho", category: GreekLower },
    MathCompletionItem { command: "sigma", snippet: "\\sigma", description: "σ sigma", category: GreekLower },
    MathCompletionItem { command: "varsigma", snippet: "\\varsigma", description: "ς variant sigma", category: GreekLower },
    MathCompletionItem { command: "tau", snippet: "\\tau", description: "τ tau", category: GreekLower },
    MathCompletionItem { command: "upsilon", snippet: "\\upsilon", description: "υ upsilon", category: GreekLower },
    MathCompletionItem { command: "phi", snippet: "\\phi", description: "φ phi", category: GreekLower },
    MathCompletionItem { command: "varphi", snippet: "\\varphi", description: "ϕ variant phi", category: GreekLower },
    MathCompletionItem { command: "chi", snippet: "\\chi", description: "χ chi", category: GreekLower },
    MathCompletionItem { command: "psi", snippet: "\\psi", description: "ψ psi", category: GreekLower },
    MathCompletionItem { command: "omega", snippet: "\\omega", description: "ω omega", category: GreekLower },
    // ── Greek uppercase ──
    MathCompletionItem { command: "Gamma", snippet: "\\Gamma", description: "Γ Gamma", category: GreekUpper },
    MathCompletionItem { command: "Delta", snippet: "\\Delta", description: "Δ Delta", category: GreekUpper },
    MathCompletionItem { command: "Theta", snippet: "\\Theta", description: "Θ Theta", category: GreekUpper },
    MathCompletionItem { command: "Lambda", snippet: "\\Lambda", description: "Λ Lambda", category: GreekUpper },
    MathCompletionItem { command: "Xi", snippet: "\\Xi", description: "Ξ Xi", category: GreekUpper },
    MathCompletionItem { command: "Pi", snippet: "\\Pi", description: "Π Pi", category: GreekUpper },
    MathCompletionItem { command: "Sigma", snippet: "\\Sigma", description: "Σ Sigma", category: GreekUpper },
    MathCompletionItem { command: "Upsilon", snippet: "\\Upsilon", description: "Υ Upsilon", category: GreekUpper },
    MathCompletionItem { command: "Phi", snippet: "\\Phi", description: "Φ Phi", category: GreekUpper },
    MathCompletionItem { command: "Psi", snippet: "\\Psi", description: "Ψ Psi", category: GreekUpper },
    MathCompletionItem { command: "Omega", snippet: "\\Omega", description: "Ω Omega", category: GreekUpper },
    // ── Big operators ──
    MathCompletionItem { command: "sum", snippet: "\\sum", description: "∑ sum", category: Operator },
    MathCompletionItem { command: "prod", snippet: "\\prod", description: "∏ product", category: Operator },
    MathCompletionItem { command: "coprod", snippet: "\\coprod", description: "∐ coproduct", category: Operator },
    MathCompletionItem { command: "int", snippet: "\\int", description: "∫ integral", category: Operator },
    MathCompletionItem { command: "iint", snippet: "\\iint", description: "∬ double integral", category: Operator },
    MathCompletionItem { command: "iiint", snippet: "\\iiint", description: "∭ triple integral", category: Operator },
    MathCompletionItem { command: "oint", snippet: "\\oint", description: "∮ contour integral", category: Operator },
    // ── Functions ──
    MathCompletionItem { command: "sin", snippet: "\\sin", description: "sin", category: Function },
    MathCompletionItem { command: "cos", snippet: "\\cos", description: "cos", category: Function },
    MathCompletionItem { command: "tan", snippet: "\\tan", description: "tan", category: Function },
    MathCompletionItem { command: "cot", snippet: "\\cot", description: "cot", category: Function },
    MathCompletionItem { command: "sec", snippet: "\\sec", description: "sec", category: Function },
    MathCompletionItem { command: "csc", snippet: "\\csc", description: "csc", category: Function },
    MathCompletionItem { command: "arcsin", snippet: "\\arcsin", description: "arcsin", category: Function },
    MathCompletionItem { command: "arccos", snippet: "\\arccos", description: "arccos", category: Function },
    MathCompletionItem { command: "arctan", snippet: "\\arctan", description: "arctan", category: Function },
    MathCompletionItem { command: "sinh", snippet: "\\sinh", description: "sinh", category: Function },
    MathCompletionItem { command: "cosh", snippet: "\\cosh", description: "cosh", category: Function },
    MathCompletionItem { command: "tanh", snippet: "\\tanh", description: "tanh", category: Function },
    MathCompletionItem { command: "log", snippet: "\\log", description: "log", category: Function },
    MathCompletionItem { command: "ln", snippet: "\\ln", description: "ln", category: Function },
    MathCompletionItem { command: "lg", snippet: "\\lg", description: "lg", category: Function },
    MathCompletionItem { command: "exp", snippet: "\\exp", description: "exp", category: Function },
    MathCompletionItem { command: "det", snippet: "\\det", description: "det", category: Function },
    MathCompletionItem { command: "dim", snippet: "\\dim", description: "dim", category: Function },
    MathCompletionItem { command: "ker", snippet: "\\ker", description: "ker", category: Function },
    MathCompletionItem { command: "deg", snippet: "\\deg", description: "deg", category: Function },
    MathCompletionItem { command: "gcd", snippet: "\\gcd", description: "gcd", category: Function },
    MathCompletionItem { command: "max", snippet: "\\max", description: "max", category: Function },
    MathCompletionItem { command: "min", snippet: "\\min", description: "min", category: Function },
    MathCompletionItem { command: "sup", snippet: "\\sup", description: "sup", category: Function },
    MathCompletionItem { command: "inf", snippet: "\\inf", description: "inf", category: Function },
    MathCompletionItem { command: "lim", snippet: "\\lim", description: "lim", category: Function },
    MathCompletionItem { command: "arg", snippet: "\\arg", description: "arg", category: Function },
    MathCompletionItem { command: "Pr", snippet: "\\Pr", description: "Pr", category: Function },
    MathCompletionItem { command: "hom", snippet: "\\hom", description: "hom", category: Function },
    // ── Relations ──
    MathCompletionItem { command: "leq", snippet: "\\leq", description: "≤ less or equal", category: Relation },
    MathCompletionItem { command: "geq", snippet: "\\geq", description: "≥ greater or equal", category: Relation },
    MathCompletionItem { command: "neq", snippet: "\\neq", description: "≠ not equal", category: Relation },
    MathCompletionItem { command: "approx", snippet: "\\approx", description: "≈ approximately", category: Relation },
    MathCompletionItem { command: "equiv", snippet: "\\equiv", description: "≡ equivalent", category: Relation },
    MathCompletionItem { command: "sim", snippet: "\\sim", description: "∼ similar", category: Relation },
    MathCompletionItem { command: "simeq", snippet: "\\simeq", description: "≃ similar equal", category: Relation },
    MathCompletionItem { command: "cong", snippet: "\\cong", description: "≅ congruent", category: Relation },
    MathCompletionItem { command: "propto", snippet: "\\propto", description: "∝ proportional", category: Relation },
    MathCompletionItem { command: "ll", snippet: "\\ll", description: "≪ much less", category: Relation },
    MathCompletionItem { command: "gg", snippet: "\\gg", description: "≫ much greater", category: Relation },
    MathCompletionItem { command: "prec", snippet: "\\prec", description: "≺ precedes", category: Relation },
    MathCompletionItem { command: "succ", snippet: "\\succ", description: "≻ succeeds", category: Relation },
    MathCompletionItem { command: "parallel", snippet: "\\parallel", description: "∥ parallel", category: Relation },
    MathCompletionItem { command: "perp", snippet: "\\perp", description: "⊥ perpendicular", category: Relation },
    MathCompletionItem { command: "models", snippet: "\\models", description: "⊨ models", category: Relation },
    MathCompletionItem { command: "vdash", snippet: "\\vdash", description: "⊢ vdash", category: Relation },
    // ── Arrows ──
    MathCompletionItem { command: "rightarrow", snippet: "\\rightarrow", description: "→ right arrow", category: Arrow },
    MathCompletionItem { command: "to", snippet: "\\to", description: "→ to", category: Arrow },
    MathCompletionItem { command: "leftarrow", snippet: "\\leftarrow", description: "← left arrow", category: Arrow },
    MathCompletionItem { command: "leftrightarrow", snippet: "\\leftrightarrow", description: "↔ left-right", category: Arrow },
    MathCompletionItem { command: "Rightarrow", snippet: "\\Rightarrow", description: "⇒ double right", category: Arrow },
    MathCompletionItem { command: "Leftarrow", snippet: "\\Leftarrow", description: "⇐ double left", category: Arrow },
    MathCompletionItem { command: "Leftrightarrow", snippet: "\\Leftrightarrow", description: "⇔ iff", category: Arrow },
    MathCompletionItem { command: "uparrow", snippet: "\\uparrow", description: "↑ up", category: Arrow },
    MathCompletionItem { command: "downarrow", snippet: "\\downarrow", description: "↓ down", category: Arrow },
    MathCompletionItem { command: "mapsto", snippet: "\\mapsto", description: "↦ maps to", category: Arrow },
    MathCompletionItem { command: "implies", snippet: "\\implies", description: "⇒ implies", category: Arrow },
    MathCompletionItem { command: "iff", snippet: "\\iff", description: "⇔ iff", category: Arrow },
    // ── Symbols ──
    MathCompletionItem { command: "partial", snippet: "\\partial", description: "∂ partial", category: Symbol },
    MathCompletionItem { command: "nabla", snippet: "\\nabla", description: "∇ nabla/del", category: Symbol },
    MathCompletionItem { command: "infty", snippet: "\\infty", description: "∞ infinity", category: Symbol },
    MathCompletionItem { command: "forall", snippet: "\\forall", description: "∀ for all", category: Symbol },
    MathCompletionItem { command: "exists", snippet: "\\exists", description: "∃ exists", category: Symbol },
    MathCompletionItem { command: "nexists", snippet: "\\nexists", description: "∄ not exists", category: Symbol },
    MathCompletionItem { command: "emptyset", snippet: "\\emptyset", description: "∅ empty set", category: Symbol },
    MathCompletionItem { command: "varnothing", snippet: "\\varnothing", description: "∅ nothing", category: Symbol },
    MathCompletionItem { command: "in", snippet: "\\in", description: "∈ element of", category: Symbol },
    MathCompletionItem { command: "notin", snippet: "\\notin", description: "∉ not in", category: Symbol },
    MathCompletionItem { command: "subset", snippet: "\\subset", description: "⊂ subset", category: Symbol },
    MathCompletionItem { command: "supset", snippet: "\\supset", description: "⊃ superset", category: Symbol },
    MathCompletionItem { command: "subseteq", snippet: "\\subseteq", description: "⊆ subset or equal", category: Symbol },
    MathCompletionItem { command: "supseteq", snippet: "\\supseteq", description: "⊇ superset or equal", category: Symbol },
    MathCompletionItem { command: "cup", snippet: "\\cup", description: "∪ union", category: Symbol },
    MathCompletionItem { command: "cap", snippet: "\\cap", description: "∩ intersection", category: Symbol },
    MathCompletionItem { command: "setminus", snippet: "\\setminus", description: "∖ set minus", category: Symbol },
    MathCompletionItem { command: "vee", snippet: "\\vee", description: "∨ or", category: Symbol },
    MathCompletionItem { command: "wedge", snippet: "\\wedge", description: "∧ and", category: Symbol },
    MathCompletionItem { command: "oplus", snippet: "\\oplus", description: "⊕ direct sum", category: Symbol },
    MathCompletionItem { command: "otimes", snippet: "\\otimes", description: "⊗ tensor product", category: Symbol },
    MathCompletionItem { command: "odot", snippet: "\\odot", description: "⊙", category: Symbol },
    MathCompletionItem { command: "times", snippet: "\\times", description: "× times", category: Symbol },
    MathCompletionItem { command: "div", snippet: "\\div", description: "÷ division", category: Symbol },
    MathCompletionItem { command: "pm", snippet: "\\pm", description: "± plus-minus", category: Symbol },
    MathCompletionItem { command: "mp", snippet: "\\mp", description: "∓ minus-plus", category: Symbol },
    MathCompletionItem { command: "cdot", snippet: "\\cdot", description: "· dot", category: Symbol },
    MathCompletionItem { command: "circ", snippet: "\\circ", description: "∘ composition", category: Symbol },
    MathCompletionItem { command: "bullet", snippet: "\\bullet", description: "• bullet", category: Symbol },
    MathCompletionItem { command: "neg", snippet: "\\neg", description: "¬ not", category: Symbol },
    MathCompletionItem { command: "therefore", snippet: "\\therefore", description: "∴ therefore", category: Symbol },
    MathCompletionItem { command: "because", snippet: "\\because", description: "∵ because", category: Symbol },
    MathCompletionItem { command: "angle", snippet: "\\angle", description: "∠ angle", category: Symbol },
    MathCompletionItem { command: "triangle", snippet: "\\triangle", description: "△ triangle", category: Symbol },
    MathCompletionItem { command: "checkmark", snippet: "\\checkmark", description: "✓", category: Symbol },
    MathCompletionItem { command: "degree", snippet: "\\degree", description: "° degree", category: Symbol },
    MathCompletionItem { command: "star", snippet: "\\star", description: "⋆ star", category: Symbol },
    // ── Delimiters ──
    MathCompletionItem { command: "langle", snippet: "\\langle", description: "⟨ left angle", category: Delimiter },
    MathCompletionItem { command: "rangle", snippet: "\\rangle", description: "⟩ right angle", category: Delimiter },
    MathCompletionItem { command: "lceil", snippet: "\\lceil", description: "⌈ left ceiling", category: Delimiter },
    MathCompletionItem { command: "rceil", snippet: "\\rceil", description: "⌉ right ceiling", category: Delimiter },
    MathCompletionItem { command: "lfloor", snippet: "\\lfloor", description: "⌊ left floor", category: Delimiter },
    MathCompletionItem { command: "rfloor", snippet: "\\rfloor", description: "⌋ right floor", category: Delimiter },
    // ── Dots ──
    MathCompletionItem { command: "ldots", snippet: "\\ldots", description: "… low dots", category: Dots },
    MathCompletionItem { command: "cdots", snippet: "\\cdots", description: "⋯ centered dots", category: Dots },
    MathCompletionItem { command: "vdots", snippet: "\\vdots", description: "⋮ vertical dots", category: Dots },
    MathCompletionItem { command: "ddots", snippet: "\\ddots", description: "⋱ diagonal dots", category: Dots },
    // ── Misc ──
    MathCompletionItem { command: "ell", snippet: "\\ell", description: "ℓ script l", category: Misc },
    MathCompletionItem { command: "hbar", snippet: "\\hbar", description: "ℏ h-bar", category: Misc },
    MathCompletionItem { command: "Re", snippet: "\\Re", description: "ℜ real part", category: Misc },
    MathCompletionItem { command: "Im", snippet: "\\Im", description: "ℑ imaginary part", category: Misc },
    MathCompletionItem { command: "aleph", snippet: "\\aleph", description: "ℵ aleph", category: Misc },
    MathCompletionItem { command: "dagger", snippet: "\\dagger", description: "† dagger", category: Misc },
    MathCompletionItem { command: "ddag", snippet: "\\ddag", description: "‡ double dagger", category: Misc },
    MathCompletionItem { command: "quad", snippet: "\\quad", description: "  em space", category: Misc },
    MathCompletionItem { command: "surd", snippet: "\\surd", description: "√ surd", category: Misc },
    MathCompletionItem { command: "colon", snippet: "\\colon", description: ": colon", category: Misc },
    MathCompletionItem { command: "top", snippet: "\\top", description: "⊤ top", category: Misc },
    MathCompletionItem { command: "bot", snippet: "\\bot", description: "⊥ bottom", category: Misc },
];

pub fn filter_math_completions(prefix: &str) -> Vec<usize> {
    let prefix = prefix.to_lowercase();
    MATH_COMPLETIONS
        .iter()
        .enumerate()
        .filter(|(_, item)| item.command.to_lowercase().starts_with(&prefix))
        .map(|(i, _)| i)
        .collect()
}

pub fn math_completion_count() -> usize {
    MATH_COMPLETIONS.len()
}

pub fn math_completion_items() -> &'static [MathCompletionItem] {
    MATH_COMPLETIONS
}
